-- CASETRACE PostgreSQL schema. Apply to a dedicated empty database.
BEGIN;

CREATE TABLE location (
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT,
    location_type TEXT NOT NULL,
    UNIQUE (name, address),
    CHECK (length(btrim(name)) > 0),
    CHECK (length(btrim(location_type)) > 0)
);

CREATE TABLE case_file (
    case_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_code VARCHAR(20) NOT NULL UNIQUE,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    incident_at TIMESTAMPTZ NOT NULL,
    location_id BIGINT NOT NULL REFERENCES location(location_id),
    status TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'CLOSED', 'ARCHIVED')),
    difficulty TEXT NOT NULL CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
    CHECK (length(btrim(title)) > 0)
);

CREATE TABLE person (
    person_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    age SMALLINT CHECK (age BETWEEN 0 AND 120),
    occupation TEXT,
    CHECK (length(btrim(full_name)) > 0)
);

CREATE TABLE case_person (
    case_id BIGINT NOT NULL REFERENCES case_file(case_id) ON DELETE CASCADE,
    person_id BIGINT NOT NULL REFERENCES person(person_id),
    case_role TEXT NOT NULL CHECK (case_role IN ('SUSPECT', 'WITNESS', 'STAFF', 'VICTIM', 'OTHER')),
    relationship_to_victim TEXT,
    case_notes TEXT,
    PRIMARY KEY (case_id, person_id)
);

CREATE TABLE evidence (
    evidence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL REFERENCES case_file(case_id) ON DELETE CASCADE,
    evidence_code VARCHAR(24) NOT NULL,
    evidence_type TEXT NOT NULL,
    description TEXT NOT NULL,
    location_id BIGINT REFERENCES location(location_id),
    discovered_at TIMESTAMPTZ,
    relevance TEXT NOT NULL CHECK (relevance IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    UNIQUE (case_id, evidence_id),
    UNIQUE (case_id, evidence_code)
);

CREATE TABLE evidence_person (
    case_id BIGINT NOT NULL,
    evidence_id BIGINT NOT NULL,
    person_id BIGINT NOT NULL,
    connection_type TEXT NOT NULL,
    PRIMARY KEY (evidence_id, person_id, connection_type),
    FOREIGN KEY (case_id, evidence_id) REFERENCES evidence(case_id, evidence_id) ON DELETE CASCADE,
    FOREIGN KEY (case_id, person_id) REFERENCES case_person(case_id, person_id) ON DELETE CASCADE
);

CREATE TABLE camera (
    camera_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL REFERENCES case_file(case_id) ON DELETE CASCADE,
    camera_code VARCHAR(24) NOT NULL,
    location_id BIGINT NOT NULL REFERENCES location(location_id),
    UNIQUE (case_id, camera_id),
    UNIQUE (case_id, camera_code)
);

CREATE TABLE cctv_observation (
    observation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL,
    camera_id BIGINT NOT NULL,
    person_id BIGINT,
    observed_at TIMESTAMPTZ NOT NULL,
    activity TEXT NOT NULL,
    confidence NUMERIC(4,3) CHECK (confidence BETWEEN 0 AND 1),
    FOREIGN KEY (case_id, camera_id) REFERENCES camera(case_id, camera_id) ON DELETE CASCADE,
    FOREIGN KEY (case_id, person_id) REFERENCES case_person(case_id, person_id)
);

CREATE TABLE access_event (
    access_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL,
    person_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL REFERENCES location(location_id),
    occurred_at TIMESTAMPTZ NOT NULL,
    access_type TEXT NOT NULL CHECK (access_type IN ('ENTRY', 'EXIT', 'DENIED', 'UNLOCK')),
    credential_code TEXT,
    FOREIGN KEY (case_id, person_id) REFERENCES case_person(case_id, person_id)
);

CREATE TABLE phone_record (
    call_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL,
    caller_id BIGINT NOT NULL,
    receiver_id BIGINT NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    duration_seconds INTEGER NOT NULL CHECK (duration_seconds BETWEEN 0 AND 86400),
    call_status TEXT NOT NULL DEFAULT 'COMPLETED' CHECK (call_status IN ('COMPLETED', 'MISSED', 'DECLINED')),
    CHECK (caller_id <> receiver_id),
    FOREIGN KEY (case_id, caller_id) REFERENCES case_person(case_id, person_id),
    FOREIGN KEY (case_id, receiver_id) REFERENCES case_person(case_id, person_id)
);

CREATE TABLE witness_statement (
    statement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL,
    witness_id BIGINT NOT NULL,
    subject_id BIGINT,
    recorded_at TIMESTAMPTZ NOT NULL,
    statement TEXT NOT NULL,
    FOREIGN KEY (case_id, witness_id) REFERENCES case_person(case_id, person_id),
    FOREIGN KEY (case_id, subject_id) REFERENCES case_person(case_id, person_id),
    CHECK (witness_id <> subject_id),
    CHECK (length(btrim(statement)) > 0)
);

CREATE TABLE vehicle (
    vehicle_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL,
    owner_id BIGINT NOT NULL,
    registration_number TEXT NOT NULL UNIQUE,
    vehicle_type TEXT NOT NULL,
    UNIQUE (case_id, vehicle_id),
    FOREIGN KEY (case_id, owner_id) REFERENCES case_person(case_id, person_id)
);

CREATE TABLE vehicle_event (
    vehicle_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL REFERENCES case_file(case_id) ON DELETE CASCADE,
    vehicle_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL REFERENCES location(location_id),
    occurred_at TIMESTAMPTZ NOT NULL,
    activity TEXT NOT NULL,
    FOREIGN KEY (case_id, vehicle_id) REFERENCES vehicle(case_id, vehicle_id) ON DELETE CASCADE
);

CREATE TABLE case_event (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL REFERENCES case_file(case_id) ON DELETE CASCADE,
    occurred_at TIMESTAMPTZ NOT NULL,
    location_id BIGINT REFERENCES location(location_id),
    event_type TEXT NOT NULL,
    description TEXT NOT NULL,
    CHECK (length(btrim(description)) > 0)
);

CREATE TABLE alibi_claim (
    claim_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL,
    person_id BIGINT NOT NULL,
    claimed_location_id BIGINT NOT NULL REFERENCES location(location_id),
    claim_start TIMESTAMPTZ NOT NULL,
    claim_end TIMESTAMPTZ NOT NULL,
    source_statement_id BIGINT REFERENCES witness_statement(statement_id),
    CHECK (claim_end > claim_start),
    FOREIGN KEY (case_id, person_id) REFERENCES case_person(case_id, person_id)
);

-- Keep the answer key in a separate relation. Do not expose it via ordinary case DTOs.
CREATE TABLE case_solution (
    case_id BIGINT PRIMARY KEY REFERENCES case_file(case_id) ON DELETE CASCADE,
    culprit_id BIGINT NOT NULL,
    method TEXT NOT NULL,
    location_id BIGINT NOT NULL REFERENCES location(location_id),
    earliest_correct_at TIMESTAMPTZ NOT NULL,
    latest_correct_at TIMESTAMPTZ NOT NULL,
    explanation TEXT NOT NULL,
    FOREIGN KEY (case_id, culprit_id) REFERENCES case_person(case_id, person_id),
    CHECK (latest_correct_at >= earliest_correct_at)
);

CREATE TABLE solution_evidence (
    case_id BIGINT NOT NULL,
    evidence_id BIGINT NOT NULL,
    PRIMARY KEY (case_id, evidence_id),
    FOREIGN KEY (case_id) REFERENCES case_solution(case_id) ON DELETE CASCADE,
    FOREIGN KEY (case_id, evidence_id) REFERENCES evidence(case_id, evidence_id)
);

CREATE TABLE solution_submission (
    submission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL REFERENCES case_file(case_id) ON DELETE CASCADE,
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    suspected_culprit_id BIGINT,
    method TEXT NOT NULL,
    location_id BIGINT REFERENCES location(location_id),
    approximate_at TIMESTAMPTZ,
    explanation TEXT NOT NULL,
    is_correct BOOLEAN NOT NULL,
    feedback TEXT NOT NULL,
    UNIQUE (submission_id, case_id),
    FOREIGN KEY (case_id, suspected_culprit_id) REFERENCES case_person(case_id, person_id)
);

CREATE TABLE submission_evidence (
    submission_id BIGINT NOT NULL,
    case_id BIGINT NOT NULL,
    evidence_id BIGINT NOT NULL,
    PRIMARY KEY (submission_id, evidence_id),
    FOREIGN KEY (submission_id, case_id) REFERENCES solution_submission(submission_id, case_id) ON DELETE CASCADE,
    FOREIGN KEY (case_id, evidence_id) REFERENCES evidence(case_id, evidence_id)
);

-- Keep case status aligned with a successful solve submission, regardless of which client submits it.
CREATE FUNCTION close_solved_case() RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.is_correct THEN
        UPDATE case_file SET status = 'CLOSED' WHERE case_id = NEW.case_id;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_close_solved_case
AFTER INSERT ON solution_submission
FOR EACH ROW
EXECUTE FUNCTION close_solved_case();

CREATE INDEX idx_case_person_role ON case_person(case_id, case_role);
CREATE INDEX idx_evidence_case_type ON evidence(case_id, evidence_type);
CREATE INDEX idx_cctv_person_time ON cctv_observation(case_id, person_id, observed_at);
CREATE INDEX idx_access_person_time ON access_event(case_id, person_id, occurred_at);
CREATE INDEX idx_access_location_time ON access_event(case_id, location_id, occurred_at);
CREATE INDEX idx_phone_participants_time ON phone_record(case_id, caller_id, receiver_id, occurred_at);
CREATE INDEX idx_case_event_time ON case_event(case_id, occurred_at);
CREATE INDEX idx_alibi_person_interval ON alibi_claim(case_id, person_id, claim_start, claim_end);

CREATE VIEW investigation_timeline_v AS
SELECT case_id, occurred_at, source_type, source_id, location_id, person_id, details
FROM (
    SELECT e.case_id, e.discovered_at AS occurred_at, 'EVIDENCE'::TEXT AS source_type,
           e.evidence_id AS source_id, e.location_id, NULL::BIGINT AS person_id,
           e.evidence_code || ': ' || e.description AS details
    FROM evidence e WHERE e.discovered_at IS NOT NULL
    UNION ALL
    SELECT o.case_id, o.observed_at, 'CCTV', o.observation_id, c.location_id, o.person_id, o.activity
    FROM cctv_observation o JOIN camera c USING (case_id, camera_id)
    UNION ALL
    SELECT a.case_id, a.occurred_at, 'ACCESS', a.access_event_id, a.location_id, a.person_id,
           a.access_type || COALESCE(' (' || a.credential_code || ')', '')
    FROM access_event a
    UNION ALL
    SELECT p.case_id, p.occurred_at, 'PHONE', p.call_id, NULL::BIGINT, p.caller_id,
           'Call to person #' || p.receiver_id || ' (' || p.call_status || ', ' || p.duration_seconds || ' sec)'
    FROM phone_record p
    UNION ALL
    SELECT ce.case_id, ce.occurred_at, 'CASE_EVENT', ce.event_id, ce.location_id, NULL::BIGINT,
           ce.event_type || ': ' || ce.description
    FROM case_event ce
    UNION ALL
    SELECT ve.case_id, ve.occurred_at, 'VEHICLE', ve.vehicle_event_id, ve.location_id, v.owner_id,
           v.registration_number || ': ' || ve.activity
    FROM vehicle_event ve JOIN vehicle v ON v.vehicle_id = ve.vehicle_id AND v.case_id = ve.case_id
) timeline;

CREATE VIEW contradiction_v AS
SELECT a.claim_id, a.case_id, a.person_id, p.full_name,
       a.claimed_location_id, claimed.name AS claimed_location,
       r.recorded_at, r.recorded_location_id, recorded.name AS recorded_location,
       r.source_type, r.source_id, r.details
FROM alibi_claim a
JOIN person p ON p.person_id = a.person_id
JOIN location claimed ON claimed.location_id = a.claimed_location_id
JOIN (
    SELECT o.case_id, o.person_id, o.observed_at AS recorded_at, c.location_id AS recorded_location_id,
           'CCTV'::TEXT AS source_type, o.observation_id AS source_id, o.activity AS details
    FROM cctv_observation o JOIN camera c USING (case_id, camera_id)
    WHERE o.person_id IS NOT NULL
    UNION ALL
    SELECT case_id, person_id, occurred_at, location_id, 'ACCESS', access_event_id,
           access_type || COALESCE(' (' || credential_code || ')', '')
    FROM access_event
) r ON r.case_id = a.case_id AND r.person_id = a.person_id
   AND r.recorded_at BETWEEN a.claim_start AND a.claim_end
   AND r.recorded_location_id <> a.claimed_location_id
JOIN location recorded ON recorded.location_id = r.recorded_location_id;

COMMIT;
