-- Add investigator authentication and activity without changing existing case data.
-- Existing solution submissions remain valid because investigator_id is nullable.
BEGIN;

CREATE TABLE IF NOT EXISTS investigator (
    investigator_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(32) NOT NULL,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_login_at TIMESTAMPTZ,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT ck_investigator_username CHECK (username ~ '^[a-z0-9._-]{3,32}$'),
    CONSTRAINT ck_investigator_email CHECK (length(btrim(email)) > 3),
    CONSTRAINT ck_investigator_password_hash CHECK (length(password_hash) >= 50),
    CONSTRAINT ck_investigator_full_name CHECK (length(btrim(full_name)) BETWEEN 1 AND 100),
    CONSTRAINT ck_investigator_status CHECK (status IN ('ACTIVE', 'LOCKED', 'DISABLED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_investigator_username_ci ON investigator (lower(username));
CREATE UNIQUE INDEX IF NOT EXISTS uq_investigator_email_ci ON investigator (lower(email));

ALTER TABLE solution_submission
    ADD COLUMN IF NOT EXISTS investigator_id BIGINT REFERENCES investigator(investigator_id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_solution_submission_investigator
    ON solution_submission(investigator_id, submitted_at DESC);

CREATE TABLE IF NOT EXISTS investigator_case_activity (
    investigator_id BIGINT NOT NULL REFERENCES investigator(investigator_id) ON DELETE CASCADE,
    case_id BIGINT NOT NULL REFERENCES case_file(case_id) ON DELETE CASCADE,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_activity_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    visit_count INTEGER NOT NULL DEFAULT 1 CHECK (visit_count > 0),
    PRIMARY KEY (investigator_id, case_id)
);

CREATE INDEX IF NOT EXISTS idx_investigator_case_activity_recent
    ON investigator_case_activity(investigator_id, last_activity_at DESC);

CREATE TABLE IF NOT EXISTS investigator_evidence_review (
    investigator_id BIGINT NOT NULL REFERENCES investigator(investigator_id) ON DELETE CASCADE,
    case_id BIGINT NOT NULL,
    evidence_id BIGINT NOT NULL,
    reviewed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (investigator_id, case_id, evidence_id),
    FOREIGN KEY (case_id, evidence_id) REFERENCES evidence(case_id, evidence_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_investigator_evidence_review_recent
    ON investigator_evidence_review(investigator_id, reviewed_at DESC);

COMMIT;
